json.id user.id
json.first_name user.first_name
json.last_name user.last_name
json.email user.email
json.gender user.gender
json.city user.city
json.state user.state
json.zip_code user.zip_code
json.image user.image
json.parent user.parent
json.nanny user.nanny